# config/packages/framework.yaml
framework:
  session:
    enabled: true
    handler_id: session.handler.native_file  # Specify a session handler
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'  # Optional: where to save session files