services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Twig\AppExtension:
        arguments:
            $sessionFactory: '@session.factory'  # Injecting the session factory
        tags:
            - { name: 'twig.extension' }

parameters:
    kernel.secret: '%env(APP_SECRET)%'  # Ensure this parameter is set